version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/users_test_task
    depends_on:
      - db
    
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_test_task
    ports:
      - "5432:5432"

  migrate:
    build: .
    depends_on:
      - db
    command: alembic upgrade head
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/users_test_task
